Another milestone reached: The system can boot and finished booting! Next step: debug why crond is not working.

diff --git a/src/rc.S/adjtimex/up b/src/rc.S/adjtimex/up
--- a/src/rc.S/adjtimex/up
+++ b/src/rc.S/adjtimex/up
@@ -1,25 +1,25 @@
-#################################################################
-# This service sets the tick and frequency for the system clock #
-#################################################################
+##################################################
+# Set the tick and frequency of the system clock #
+##################################################
 
-foreground { echo "Starting oneshot service:  adjtimex" }
+backtick -ni ADJTIMEX { which adjtimex }
+importas -u adjtimex ADJTIMEX
 # Default values are: TICK=10000 and FREQ=0. If there's a
 # /etc/default/adjtimex config file, source it to override
 # the default TICK and FREQ.
-ifelse -n { [ -r /etc/default/adjtimex ] }
+ifelse { [ ! -r /etc/default/adjtimex ] }
 {
-  foreground { echo "Setting the system clock rate:  adjtimex --tick 10000 --frequency 0" }
-  adjtimex --tick 10000 --frequency 0
+  foreground { echo "adjtimex: Setting the system clock rate: ${adjtimex} --tick 10000 --frequency 0" }
+  $adjtimex --tick 10000 --frequency 0
 }
 envfile /etc/default/adjtimex
 multisubstitute {
   importas -u tick TICK
   importas -u freq FREQ
 }
-ifelse { adjtimex --tick $tick --frequency $freq }
+ifelse { $adjtimex --tick $tick --frequency $freq }
 {
-  echo "Setting the system clock rate:  adjtimex --tick $tick --frequency $freq"
+  echo "adjtimex: Setting the system clock rate: ${adjtimex} --tick ${tick} --frequency ${freq}"
 }
-echo "Failed to set system clock with adjtimex, possibly invalid parameters?\
-(TICK=${tick} FREQ=${freq})
-(ERROR) Failed to start oneshot service:  adjtimex"
+foreground { echo "adjtimex: Failed to set system clock with adjtimex, possibly invalid parameters? (TICK=${tick} FREQ=${freq})" }
+exit 1
